# YOUR NAME OR TITLE OF YOUR SITE
name: DC9111

# YOUR BRAND/PERSONAL TAGLINE
tagline: For the Hackers, By the Hackers

# YOUR/BRAND IMAGE URL
Image_URL: https://github.com/dc-9111.png

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/random

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # FACEBOOK
  - Name: Facebook
    URL: https://www.facebook.com
    Username: dc9111
    Color: '#3b5998'
    Icon-Class: fab fa-facebook

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: dc_9111
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # TWITTER
  - Name: Twitter
    URL: https://twitter.com
    Username: dc_9111
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter
    
    # LINKEDIN
  - Name: LinkedIn
    URL: https://www.linkedin.com/company
    Username: dc-9111
    Color: '#2867B2'
    Icon-Class: fab fa-linkedin-in

    # YOUTUBE
  - Name: YouTube
    URL: https://www.youtube.com/channel
    Username: UCpHngVxoYmSBG5Yp2An3bTQ
    Color: '#ff0000'
    Icon-Class: fab fa-youtube

    # GITHUB
  - Name: GitHub
    URL: http://github.com
    Username: dc-9111
    Color: '#6e5494'
    Icon-Class: fab fa-github

    # EMAIL
  - Name: Email
    URL: 'mailto:mail@defcon9111.org'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'

    # TWITCH
  - Name: Twitch
    URL: 'https://twitch.tv'
    Username: dc_9111
    Icon-Class: fab fa-twitch
    Color: '#9147fe'
    Text_Color: '#ffffff'

    # MESSENGER
  - Name: Messenger
    URL: https://m.me
    Username: dc_9111
    Color: '#006AFF'
    Icon-Class: fab fa-facebook-messenger

    # DISCORD
  - Name: Discord
    URL: 'https://discord.gg'
    Username: tchsmJ8ZZQ
    Icon-Class: fab fa-discord
    Color: '#5865F2'
    Text_Color: '#ffffff'
    
      # BUY ME A COFFEE
  - Name: Donate
    URL: 'https://www.buymeacoffee.com/defcon9111'
    Username: tchsmJ8ZZQ
    Icon-Class: fas fa-mug-hot
    Color: '#40dca5'
    Text_Color: '#ffffff'
    
    # MEDIUM
  - Name: Medium
    URL: 'https://medium.com'
    Username: '@dcg9111'
    Icon-Class: fab fa-medium-m
    Color: '#00ab6c'
    Text_Color: '#ffffff'

    # CUSTOM LINK
  - Name: DC9111
    URL: https://defcon9111.org/
    Icon-Class: fas fa-link
    Color: '#ffb142'
    Text_Color: '#ffffff'
    
    
    # 0X04 LINK
  - Name: 0x04
    URL: https://forms.gle/Gfga3VEtqPGUL4jB6
    Icon-Class: fas fa-link
    Color: '#ffb142'
    Text_Color: '#ffffff'

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'No'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
baseurl: /links

# Default Markdown Engine
markdown: kramdown
